### ISSUE TITLE
New Version of Source Code (v1.6)

### ISSUE THREAD

**Issue by NariGODs** [RunnyBore604/standaloneGRBL#6]
Good day everyone,
I want to know where i can found the source code of the new version of the 2 axis software.
Image-to-Gcode v1.6.

Best Reggards

**Comment by RunnyBore604** [comment]
https://yadi.sk/d/MX3bjFuf3YxGkU - image2gcode, v1.6 + src

**Comment by luisluna2** [comment]
> https://yadi.sk/d/MX3bjFuf3YxGkU - image2gcode, v1.6 + src

Amazing Work! About of the source code for 3/4 axis, can share with me? I'm working in this now but I have some problems with solve SD Module.
